huatrack/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from website import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^website/', include('website.urls')),
    url(r'^log_out/$', views.log_out, name='log_out'),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from website import views

app_name = 'website'

urlpatterns = [
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_reg/$', views.user_reg, name='user_reg'),
    url(r'^collection/$', views.collection, name='collection'),
    url(r'^artwork_reg/$', views.artwork_reg, name='artwork_reg'),
    url(r'^artwork_detail/(?P<artwork_id>\d+)/$', views.artwork_detail, name='artwork_detail'),
    url(r'^asset_get/(?P<artwork_id>\d+)/$', views.asset_get, name='asset_get'),
    url(r'^asset_create/(?P<artwork_id>\d+)/$', views.asset_create, name='asset_create'),
    url(r'^asset_transfer/(?P<artwork_id>\d+)/$', views.asset_transfer, name='asset_transfer'),
    url(r'^profile/$', views.profile, name='profile'),
]

website/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    public_key = models.CharField(max_length=255, null=True, blank=True)
    private_key = models.CharField(max_length=255, null=True, blank=True)
    dp = models.ImageField(verbose_name='dp', upload_to='dp', blank=True, null=True)


class Artwork(models.Model):
    title = models.CharField(max_length=255)
    created = models.CharField(max_length=255)
    timestamp = models.DateTimeField(max_length=255)
    artist = models.CharField(max_length=255)
    hash = models.CharField(max_length=255)
    path = models.ImageField(verbose_name='path', upload_to='artwork', blank=True, null=True)
    txid = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=255, null=True, blank=True)

website/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Artwork, UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ArtworkForm(forms.ModelForm):

    class Meta:
        model = Artwork
        fields = ['title', 'created', 'path']
        widgets = {
            'created': forms.DateInput(attrs={'id': 'date', 'class': 'datepicker'})
        }

    def __init__(self, *args, **kwargs):
        super(ArtworkForm, self).__init__(*args, **kwargs)
        self.fields['path'].widget.attrs.update({'class': 'file-path validate'})


class ProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['public_key', 'private_key']


class ArtworkTransferForm(forms.ModelForm):

    class Meta:
        model = Artwork
        fields = ['txid']

website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ArtworkForm, ProfileForm, ArtworkTransferForm
from .models import UserProfile, Artwork, User
import time
import datetime
# import hashlib
import bigchaindb_driver
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
import json
from time import sleep
from django.http import JsonResponse
from bigchaindb_driver.exceptions import NotFoundError


def index(request):
    data = {'artworks': ''}
    return render(request, 'website/index.html', data)


def gallery(request):
    data = {'artworks': 'artworks'}
    return render(request, 'website/gallery.html', data)


@login_required
def profile(request):
    user = request.user
    data = {
        'user': user,
    }
    return render(request, 'user/profile.html', data)


@login_required
def collection(request):
    public_key = request.user.userprofile.public_key
    collection = Artwork.objects.filter(artist=public_key)

    data = {
        'collection': collection,
    }
    return render(request, 'user/collection.html', data)


@login_required
def artwork_detail(request, artwork_id):
    artwork = Artwork.objects.get(id=artwork_id)
    data = {
        'artwork': artwork,
    }
    return render(request, 'user/artwork_detail.html', data)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('../collection')
            else:
                return HttpResponse('account is not active')
        else:
            return render(request, 'user/login.html', {'form_errors': 'User not exist'})
    else:
        return render(request, 'user/login.html')


@login_required
def log_out(request):
    logout(request)
    return redirect('../website/user_login')


def user_reg(request):
    user_form = UserForm
    profile_form = ProfileForm

    data = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        data['user_form'] = user_form
        data['profile_form'] = profile_form

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save(commit=False)
            password = user_form.cleaned_data['password']
            user.set_password(password)
            user_form.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            keys = generate_keypair()
            profile.public_key = keys.public_key
            profile.private_key = keys.private_key
            profile.save()

            return redirect('../user_login')
        else:
            data['form_errors'] = 'Invalid Form'
            return render(request, 'user/register.html', data)
    else:
        return render(request, 'user/register.html', data)


@login_required()
def artwork_reg(request):
    form = ArtworkForm

    data = {
        'form': form,
    }

    if request.method == 'POST':
        form = ArtworkForm(request.POST, request.FILES)
        data['form'] = form

        if form.is_valid():
            artwork = form.save(commit=False)
            artwork.timestamp = datetime.datetime.now()
            artwork.artist = request.user.userprofile.public_key
            artwork.status = 'pending'
            artwork.save()
            return redirect('../collection')
        else:
            print(form.errors)
            data['form_errors'] = 'Invalid Form'
            return render(request, 'user/artwork_form.html', data)
    else:
        return render(request, 'user/artwork_form.html', data)


@login_required()
def asset_create(request, artwork_id):
    tokens = {'app_id': '186018c8', 'app_key': 'd317b3d1bb45c984d817c498770c47c0'}
    bdb = BigchainDB('https://test.bigchaindb.com', headers=tokens)

    data = {
        'status': False
    }
    user_public_key = request.user.userprofile.public_key
    user_private_key = request.user.userprofile.private_key

    artwork = Artwork.objects.filter(id=artwork_id)
    for art in artwork:
        art_title = art.title
        art_created = art.created
        art_hash = art.hash
        art_path = art.path.url

    art = {
        'data': {
            'art': {
                'title': art_title,
                'created': art_created,
                'timestamp': time.time(),
                'hash': art_hash,
                'path': art_path,
            },
        },
    }
    metadata = {'Developer': 'Engr. Ijazul Haq'}
    prepared_creation_tx = bdb.transactions.prepare(
        operation='CREATE',
        signers=user_public_key,
        asset=art,
        metadata=metadata,
    )

    fulfilled_creation_tx = bdb.transactions.fulfill(
        prepared_creation_tx,
        private_keys=user_private_key,
    )
    
    bdb.transactions.send(fulfilled_creation_tx)

    txid = fulfilled_creation_tx['id']

    trials = 0

    while trials < 100:
        try:
            if bdb.transactions.status(txid).get('status') == 'valid':
                break
        except bigchaindb_driver.exceptions.NotFoundError:
            trials += 1
    tx_status = bdb.transactions.status(txid)

    if tx_status == 'valid':
        artwork.status = 'registered'
        artwork.save()
        data['status'] = 'valid'
    else:
        data['status'] = 'invalid'

    return JsonResponse(data)


@login_required()
def asset_transfer(request, artwork_id):
    data = {}
    if request.method == 'POST':
        email = request.POST.get('email')
        txid = request.POST.get('txid')
        new_owner = User.objects.filter(email=email)
        if new_owner.count() == 1:
            for n in new_owner:
                new_owner_public_key = n.userprofile.public_key
                old_owner_private_key = request.user.userprofile.private_key
                old_owner_public_key = request.user.userprofile.public_key

                if new_owner_public_key == request.user.userprofile.public_key:
                    data['errors'] = 'You cannot transfer to yourself'
                    return render(request, 'user/collection.html', data)
                else:
                    tokens = {'app_id': '186018c8', 'app_key': 'd317b3d1bb45c984d817c498770c47c0'}
                    bdb = BigchainDB('https://test.bigchaindb.com', headers=tokens)
                    asset = bdb.transactions.retrieve(txid)
                    print(old_owner_public_key)
                    print('\n')
                    print(asset['inputs'][0]['owners_before'][0])
                    if asset:
                        if old_owner_public_key != asset['inputs'][0]['owners_before'][0]:
                            data['errors'] = 'Sorry! this Artwork is not yours'
                        else:
                            transfer_asset = {
                                'id': asset['id']
                            }
                            output_index = 0
                            output = asset['outputs'][output_index]

                            transfer_input = {
                                'fulfillment':
                                    output['condition']['details'],
                                'fulfills': {
                                    'output_index': output_index,
                                    'transaction_id': asset['id'],
                                    },
                                'owners_before': output['public_keys'],
                            }
                            prepared_transfer_tx = bdb.transactions.prepare(
                                operation='TRANSFER',
                                asset=transfer_asset,
                                inputs=transfer_input,
                                recipients=new_owner_public_key,
                            )
                            fulfilled_transfer_tx = bdb.transactions.fulfill(
                                prepared_transfer_tx,
                                private_keys=old_owner_private_key,
                            )
                            sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)
                            new_owner_public_key = sent_transfer_tx['outputs'][0]['public_keys'][0]
                            data['new_owner']=new_owner_public_key
                            return JsonResponse(data)
                    else:
                        data['errors'] = 'Asset not found on Blockchain'
        else:
            data['errors'] = 'Recipient not found'
    else:
        data['errors'] = 'Request time out, try again'
    return render(request, 'user/collection.html', data)


@login_required()
def asset_get(request, artwork_id):
    artwork = Artwork.objects.get(id=artwork_id)
    status = False
    tokens = {'app_id': '186018c8', 'app_key': 'd317b3d1bb45c984d817c498770c47c0'}
    bdb = BigchainDB('https://test.bigchaindb.com', headers=tokens)

    if artwork.txid:
        status = bdb.transactions.status(artwork.txid)

    data = {
        'status': status,
    }
    return JsonResponse(data)

website/templates/website/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <title>Huatrack</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/materialize.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/materialize.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/js.js' %}" type="text/javascript"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
</head>
<body>
<header>
    <nav class="z-depth-0 cyan darken-3">
        <div class="nav-wrapper">
            <a href="{% url 'index' %}" class="brand-logo shadow-2">HUATRACK</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'index' %}">HOME</a></li>
                <li><a href="{% url 'website:gallery' %}">GALLERY</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'website:collection' %}">ME</a></li>
                {% else %}
                <li><a href="{% url 'website:user_login' %}">LOGIN</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block slider %}
{#        Here is the slider#}
    {% endblock %}
</header>
<div class="container z-depth-1" id="main-container">
    {% block main_content %}

    {% endblock %}
</div>
<footer class="page-footer cyan darken-2">
    <div class="container">
        <div class="row empty-1"></div>
        <div class="row">
            <div class="col s6">
                <a href="http://www.facebook.com/ijaz716" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-facebook z-depth-1"></i></a>
                <a href="http://www.linkedin.com/in/ijaz716" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-linkedin z-depth-1"></i></a>
                <a href="http://www.twitter.com/ijazulhaq_pk" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-twitter z-depth-1"></i></a>
                <a href="http://www.creativexlab.com" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-globe z-depth-1"></i></a>
            </div>
            <div class="col s6">
                <h6><a target="_blank" href="https://github.com/ijazul-haq/trueart" class="white-text"><i class="fa fa-github"></i>
                    &nbsp; View on Gighub</a></h6>
                <h6><a target="_blank" href="https://github.com/ijazul-haq/trueart" class="white-text"><i class="fa fa-file-pdf-o"></i>
                    &nbsp; White Paper</a></h6>
            </div>
        </div>

        <div class="row empty-1"></div>
    </div>
    <div class="footer-copyright cyan darken-3">
        <div class="container center">
            Copyrights © 2017: Ijazul Haq, International School of Software, Wuhan University, China.
        </div>
    </div>
</footer>
</body>
</html>

website/templates/website/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
</form>
</body>
</html>

website/templates/website/gallery.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% load staticfiles %}
{% block slider %}
{#    {% include 'website/slider.html' %}#}
{% endblock %}
{% block main_content %}
    <div class="empty-2"></div>
    <div class="row">
        <div class="col m4">
            <div class="card z-depth-half">
                <div class="row center">
                    <div class="col s12">
                        <img class="responsive-img" src="{% static 'img/slide4.jpg' %}" alt="no"/>
                    </div>
                    <div class="col s12">
                        <h6><b>Wuhan University</b></h6>
                        <h6>by Ijazul Haq: <em>2017</em></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/website/index.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% block slider %}
    {% include 'website/slider.html' %}
{% endblock %}
{% block main_content %}
    <h1>Here is the Main container</h1>
{% endblock %}

website/templates/website/slider.html
<!DOCTYPE html>
{% load static %}
<div class="slider fullscreen">
    <ul class="slides">
        <li>
            <img src="{% static 'img/slide4.jpg' %}">
        </li>
        <li>
            <img src="{% static 'img/slide2.jpg' %}">
        </li>
        <li>
            <img src="{% static 'img/slide3.jpg' %}">
        </li>
        <li>
            <img src="{% static 'img/slide1.jpg' %}">
        </li>
        <li>
            <img src="{% static 'img/slide5.jpg' %}">
        </li>
    </ul>
</div>
<div class="card overlay center transparent white-text text-darken-4 z-depth-0">
    <h3 class="shadow-1 white-text">Welcome to HuaTrack.com</h3>
    <h5 class="shadow-2 white-text">A Blockchain based tracking system for Artwork</h5><br>
    <a href="website/artwork_reg/" class="btn btn-large">Register Your Artwork</a>
</div>