huatrack/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from website import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^website/', include('website.urls')),
    url(r'^log_out/$', views.log_out, name='log_out'),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from website import views

app_name = 'website'

urlpatterns = [
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_reg/$', views.user_reg, name='user_reg'),
    url(r'^collection/$', views.collection, name='collection'),
    url(r'^artwork_reg/$', views.artwork_reg, name='artwork_reg'),
    url(r'^artwork_detail/(?P<artwork_id>\d+)/$', views.artwork_detail, name='artwork_detail'),
    url(r'^asset_get/(?P<artwork_id>\d+)/$', views.asset_get, name='asset_get'),
    url(r'^asset_create/(?P<artwork_id>\d+)/$', views.asset_create, name='asset_create'),
    url(r'^asset_transfer/(?P<artwork_id>\d+)/$', views.asset_transfer, name='asset_transfer'),
    url(r'^profile/$', views.profile, name='profile'),
]

website/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    public_key = models.CharField(max_length=255, null=True, blank=True)
    private_key = models.CharField(max_length=255, null=True, blank=True)
    dp = models.ImageField(verbose_name='dp', upload_to='dp', blank=True, null=True)


class Artwork(models.Model):
    title = models.CharField(max_length=255)
    created = models.CharField(max_length=255)
    timestamp = models.DateTimeField(max_length=255)
    artist = models.CharField(max_length=255)
    hash = models.CharField(max_length=255)
    path = models.ImageField(verbose_name='path', upload_to='artwork', blank=True, null=True)
    txid = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=255, null=True, blank=True)

website/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Artwork, UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ArtworkForm(forms.ModelForm):

    class Meta:
        model = Artwork
        fields = ['title', 'created', 'path']
        widgets = {
            'created': forms.DateInput(attrs={'id': 'date', 'class': 'datepicker'})
        }

    def __init__(self, *args, **kwargs):
        super(ArtworkForm, self).__init__(*args, **kwargs)
        self.fields['path'].widget.attrs.update({'class': 'file-path validate'})


class ProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['public_key', 'private_key']


class ArtworkTransferForm(forms.ModelForm):

    class Meta:
        model = Artwork
        fields = ['txid']

website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ArtworkForm, ProfileForm, ArtworkTransferForm
from .models import UserProfile, Artwork, User
import time
import datetime
# import hashlib
import bigchaindb_driver
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
import json
from time import sleep
from django.http import JsonResponse
from bigchaindb_driver.exceptions import NotFoundError


def index(request):
    data = {'artworks': ''}
    return render(request, 'website/index.html', data)


def gallery(request):
    data = {'artworks': 'artworks'}
    return render(request, 'website/gallery.html', data)


@login_required
def profile(request):
    user = request.user
    data = {
        'user': user,
    }
    return render(request, 'user/profile.html', data)


@login_required
def collection(request):
    public_key = request.user.userprofile.public_key
    collection = Artwork.objects.filter(artist=public_key)

    data = {
        'collection': collection,
    }
    return render(request, 'user/collection.html', data)


@login_required
def artwork_detail(request, artwork_id):
    artwork = Artwork.objects.get(id=artwork_id)
    data = {
        'artwork': artwork,
    }
    return render(request, 'user/artwork_detail.html', data)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('../collection')
            else:
                return HttpResponse('account is not active')
        else:
            return render(request, 'user/login.html', {'form_errors': 'User not exist'})
    else:
        return render(request, 'user/login.html')


@login_required
def log_out(request):
    logout(request)
    return redirect('../website/user_login')


def user_reg(request):
    user_form = UserForm
    profile_form = ProfileForm

    data = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        data['user_form'] = user_form
        data['profile_form'] = profile_form

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save(commit=False)
            password = user_form.cleaned_data['password']
            user.set_password(password)
            user_form.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            keys = generate_keypair()
            profile.public_key = keys.public_key
            profile.private_key = keys.private_key
            profile.save()

            return redirect('../user_login')
        else:
            data['form_errors'] = 'Invalid Form'
            return render(request, 'user/register.html', data)
    else:
        return render(request, 'user/register.html', data)


@login_required()
def artwork_reg(request):
    form = ArtworkForm

    data = {
        'form': form,
    }

    if request.method == 'POST':
        form = ArtworkForm(request.POST, request.FILES)
        data['form'] = form

        if form.is_valid():
            artwork = form.save(commit=False)
            artwork.timestamp = datetime.datetime.now()
            artwork.artist = request.user.userprofile.public_key
            artwork.status = 'pending'
            artwork.save()
            return redirect('../collection')
        else:
            print(form.errors)
            data['form_errors'] = 'Invalid Form'
            return render(request, 'user/artwork_form.html', data)
    else:
        return render(request, 'user/artwork_form.html', data)


@login_required()
def asset_create(request, artwork_id):
    tokens = {'app_id': '186018c8', 'app_key': 'd317b3d1bb45c984d817c498770c47c0'}
    bdb = BigchainDB('https://test.bigchaindb.com', headers=tokens)

    data = {
        'status': False
    }
    user_public_key = request.user.userprofile.public_key
    user_private_key = request.user.userprofile.private_key

    artwork = Artwork.objects.filter(id=artwork_id)
    for art in artwork:
        art_title = art.title
        art_created = art.created
        art_hash = art.hash
        art_path = art.path.url

    art = {
        'data': {
            'art': {
                'title': art_title,
                'created': art_created,
                'timestamp': time.time(),
                'hash': art_hash,
                'path': art_path,
            },
        },
    }
    metadata = {'Developer': 'Engr. Ijazul Haq'}
    prepared_creation_tx = bdb.transactions.prepare(
        operation='CREATE',
        signers=user_public_key,
        asset=art,
        metadata=metadata,
    )

    fulfilled_creation_tx = bdb.transactions.fulfill(
        prepared_creation_tx,
        private_keys=user_private_key,
    )
    
    bdb.transactions.send(fulfilled_creation_tx)

    txid = fulfilled_creation_tx['id']

    trials = 0

    while trials < 100:
        try:
            if bdb.transactions.status(txid).get('status') == 'valid':
                break
        except bigchaindb_driver.exceptions.NotFoundError:
            trials += 1
    tx_status = bdb.transactions.status(txid)

    if tx_status == 'valid':
        artwork.status = 'registered'
        artwork.save()
        data['status'] = 'valid'
    else:
        data['status'] = 'invalid'

    return JsonResponse(data)


@login_required()
def asset_transfer(request, artwork_id):
    data = {}
    if request.method == 'POST':
        email = request.POST.get('email')
        txid = request.POST.get('txid')
        new_owner = User.objects.filter(email=email)
        if new_owner.count() == 1:
            for n in new_owner:
                new_owner_public_key = n.userprofile.public_key
                old_owner_private_key = request.user.userprofile.private_key
                old_owner_public_key = request.user.userprofile.public_key

                if new_owner_public_key == request.user.userprofile.public_key:
                    data['errors'] = 'You cannot transfer to yourself'
                    return render(request, 'user/collection.html', data)
                else:
                    tokens = {'app_id': '186018c8', 'app_key': 'd317b3d1bb45c984d817c498770c47c0'}
                    bdb = BigchainDB('https://test.bigchaindb.com', headers=tokens)
                    asset = bdb.transactions.retrieve(txid)
                    print(old_owner_public_key)
                    print('\n')
                    print(asset['inputs'][0]['owners_before'][0])
                    if asset:
                        if old_owner_public_key != asset['inputs'][0]['owners_before'][0]:
                            data['errors'] = 'Sorry! this Artwork is not yours'
                        else:
                            transfer_asset = {
                                'id': asset['id']
                            }
                            output_index = 0
                            output = asset['outputs'][output_index]

                            transfer_input = {
                                'fulfillment':
                                    output['condition']['details'],
                                'fulfills': {
                                    'output_index': output_index,
                                    'transaction_id': asset['id'],
                                    },
                                'owners_before': output['public_keys'],
                            }
                            prepared_transfer_tx = bdb.transactions.prepare(
                                operation='TRANSFER',
                                asset=transfer_asset,
                                inputs=transfer_input,
                                recipients=new_owner_public_key,
                            )
                            fulfilled_transfer_tx = bdb.transactions.fulfill(
                                prepared_transfer_tx,
                                private_keys=old_owner_private_key,
                            )
                            sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)
                            new_owner_public_key = sent_transfer_tx['outputs'][0]['public_keys'][0]
                            data['new_owner']=new_owner_public_key
                            return JsonResponse(data)
                    else:
                        data['errors'] = 'Asset not found on Blockchain'
        else:
            data['errors'] = 'Recipient not found'
    else:
        data['errors'] = 'Request time out, try again'
    return render(request, 'user/collection.html', data)


@login_required()
def asset_get(request, artwork_id):
    artwork = Artwork.objects.get(id=artwork_id)
    status = False
    tokens = {'app_id': '186018c8', 'app_key': 'd317b3d1bb45c984d817c498770c47c0'}
    bdb = BigchainDB('https://test.bigchaindb.com', headers=tokens)

    if artwork.txid:
        status = bdb.transactions.status(artwork.txid)

    data = {
        'status': status,
    }
    return JsonResponse(data)

website/templates/user/artwork_detail.html
<!DOCTYPE html>
{% extends 'user/base.html' %}
{% load staticfiles %}

{% block page_title %}
    <a href="{% url 'website:collection' %}"><i class="fa fa-arrow-left"></i></a>
    &nbsp; Collection / {{ artwork.title }}
{% endblock %}

{% block user_nave %}
    <li><a href="#"><i class="fa fa-trash-o"></i> Delete</a></li>
    <li><a href="#"><i class="fa fa-download"></i> Download</a></li>
    <li><a href="#modal" class="modal-trigger"><i class="fa fa-share"></i> Transfer</a></li>
{% endblock %}

{% block errors %}
    {{ errors }}
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col l5">
            <img class="responsive-img z-depth-1" src="{{ artwork.path.url }}">
        </div>
        <div class="col l7">
            <div class="row">
                <div class="col l12">
                    <table class="responsive-table small-text condensed">
                        <tr>
                            <td>Title:</td>
                            <td>{{ artwork.title }}</td>
                        </tr>
                        <tr>
                            <td>Date of Creation:</td>
                            <td>{{ artwork.created }}</td>
                        </tr>
                        <tr>
                            <td>Registered On:</td>
                            <td>{{ artwork.timestamp }}</td>
                        </tr>
                        <tr>
                            <td>Status:</td>
                            <td>{{ artwork.status }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="divider"></div>
            <h6>Blockchain Info</h6>
            <div class="row">
                <div class="{% if artwork.status != 'registered' %}hide{% endif %} col l12" id="bc-info">
                    <table class="responsive-table small-text condensed">
                        <tr>
                            <td>Owner ID:</td>
                            <td id="tx-id">{{ artwork.artist }}</td>
                        </tr>
                        <tr>
                            <td>ID:</td>
                            <td id="tx-id">{{ artwork.txid }}</td>
                        </tr>
                    </table>
                </div>
                <div class="{% if artwork.status == 'registered' %}hide{% endif %} col l12" id="bc-action">
                    <h6><b class="red-text">No Blockchain info available right now</b></h6>
                    <div class="empty-2"></div>
                    <a href="{% url 'website:asset_create' artwork.id %}" class="btn red" id="asset-creat">
                        <i class="fa fa-lock"></i> PUSH TO BLOCKCHAIN
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="empty-2"></div>
    <div id="modal" class="modal">
        <div class="modal-content">
            <h4>Transfer Artwork</h4>
            <form method="post" action="{% url 'website:asset_transfer' artwork.id%}">
                {% csrf_token %}
                <div class="row">
                    <div class="col l10 offset-l1 input-field">
                        <input type="email" name="email">
                        <label for="title">Recipient Email:</label>
                    </div>
                    <div class="col l10 offset-l1 input-field hidden">
                        <input type="text" name="txid" value="{{ artwork.txid }}" class="hide">
                    </div>
                    <div class="col l10 offset-l1 input-field">
                        <input class="btn modal-action modal-close" type="submit" value="SEND">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

website/templates/user/artwork_form.html
<!DOCTYPE html>
{% extends 'user/base.html' %}
{% load staticfiles %}
{% block page_title %}Add New Artwork{% endblock %}
{% block main_content %}
    <div class="row center">
    <p style="color: red;">{{ form_errors }}</p>
        <div class="col s12 m10 offset-m1">
            <form method="post" action="{% url 'website:artwork_reg' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field file-field  col s12">
                        <div class="btn cyan darken-1">
                            <span>UPLOAD FILE</span>
                            <input type="file">
                        </div>
                        <div class="file-path-wrapper">
                            {{ form.path }}
{#                                                        <input class="file-path validate" type="text">#}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{ form.title }}
                        <label for="title">Title</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{ form.created }}
                        <label for="title">Date</label>
                    </div>
                </div>
                <div class="row center">
                    <div class="input-field col s12">
                        <input type="submit" value="REGISTER" class="validate btn cyan darken-3">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

website/templates/user/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <title>Huatrack</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/materialize.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/materialize.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/js.js' %}" type="text/javascript"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
</head>
<body>
<header>
    <nav class="z-depth-0 cyan darken-4">
        <div class="nav-wrapper">
            <a href="{% url 'index' %}" class="brand-logo shadow-2">HUATRACK</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href='{% url 'website:artwork_reg' %}'><i class="fa fa-plus"></i> Add New</a></li>
                <li><a href="{% url 'website:collection' %}"><i class="fa fa-list"></i> Collection</a></li>
                <li><a href="{% url 'website:profile' %}"><i class="fa fa-user"></i> Profile</a></li>
                <li><a href="{% url 'log_out' %}"><i class="fa fa-power-off" title="Logout"></i></a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="container z-depth-1" id="main-container">
    <div class="row user-nav z-depth-half cyan-text text-darken-3">
        <div class="col s7">
            <div class="page-title">
                {% block page_title %}

                {% endblock %}
            </div>
        </div>
        <div class="col s5">
            <ul class="">
                {% block user_nave %}
                {% endblock %}
            </ul>
        </div>
    </div>
    {% block errors %}

    {% endblock %}

    <div class="empty-2"></div>
    {% block main_content %}

    {% endblock %}
</div>
<footer class="page-footer cyan darken-2">
    <div class="container">
        <div class="row empty-1"></div>
        <div class="row">
            <div class="col s6">
                <a href="http://www.facebook.com/ijaz716" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-facebook z-depth-1"></i></a>
                <a href="http://www.linkedin.com/in/ijaz716" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-linkedin z-depth-1"></i></a>
                <a href="http://www.twitter.com/ijazulhaq_pk" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-twitter z-depth-1"></i></a>
                <a href="http://www.creativexlab.com" target="_blank"><i
                        class="icon cyan darken-3 white-text fa fa-globe z-depth-1"></i></a>
            </div>
            <div class="col s6">
                <h6><a target="_blank" href="https://github.com/ijazul-haq/trueart" class="white-text"><i
                        class="fa fa-github"></i>
                    &nbsp; View on Gighub</a></h6>
                <h6><a target="_blank" href="https://github.com/ijazul-haq/trueart" class="white-text"><i
                        class="fa fa-file-pdf-o"></i>
                    &nbsp; White Paper</a></h6>
            </div>
        </div>

        <div class="row empty-1"></div>
    </div>
    <div class="footer-copyright cyan darken-3">
        <div class="container center">
            Copyrights © 2017: Ijazul Haq, International School of Software, Wuhan University, China.
        </div>
    </div>
</footer>
</body>
</html>

website/templates/user/bdb.html
<!DOCTYPE html>
{% extends 'user/base.html' %}
{% load staticfiles %}
{% block page_title %}Blockchan Status{% endblock %}
{% block user_nave %}
    <li><a href="setting.html"><i class="fa fa-gear"></i></a></li>
{% endblock %}
{% block main_content %}

    {{ sent_tx }}
    <hr>
    {{ txid }}
    <hr>
    {{ status }}
    <hr>
    {{ bdb }}


{% endblock %}

website/templates/user/collection.html
<!DOCTYPE html>
{% extends 'user/base.html' %}
{% load staticfiles %}
{% block page_title %}Collection{% endblock %}

{% block errors %}
    {% if errors %}
        <div class="row errors">
            <div class="col">
                {{ errors }}
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block main_content %}
    <div class="row user-collection">
        {% for artwork in collection %}
            <div class="col m4">
                <a href="{% url 'website:artwork_detail' artwork.id %}">
                    <div class="card center">
                        <div class="card-image responsive-img">
                            <img src="{{ artwork.path.url }}">
                        </div>
                        <div class="card-content">
                            <h6>{{ artwork.title }}</h6>
                            <span>{{ artwork.created }}</span>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <div class="empty-2"></div>
{% endblock %}

website/templates/user/login.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% block main_content %}
    <div class="row center">
        <h4>Login</h4>
        <p style="color: red;">{{ form_errors }}</p>
        <form class="col s12" method="post" action="{% url 'website:user_login' %}">
            {% csrf_token %}
            <div class="row cyan-text text-darken-2">
                <div class="empty-1"></div>
                <div class="input-field col s6 offset-s3">
                    <i class="fa fa-user-circle prefix"></i>
                    <input id="icon_prefix" type="text" name="username" class="validate">
                    <label for="icon_prefix">Username or Email Address</label>
                </div>
                <div class="input-field col s6 offset-s3">
                    <i class="fa fa-key prefix"></i>
                    <input id="icon_telephone" type="password" name="password" class="validate">
                    <label for="icon_prefix">Password</label>
                </div>
                <div class="input-field col s6 offset-s3">
                    <input type="submit" class="btn btn-large" value="LOGIN">
                </div>
                <div class="input-field col s6 offset-s3">
                    If you don't have account please <a href="{% url 'website:user_reg' %}">Register</a>.
                </div>
            </div>
        </form>
    </div>
{% endblock %}

website/templates/user/profile.html
<!DOCTYPE html>
{% extends 'user/base.html' %}
{% load staticfiles %}
{% block page_title %}Profile Setting{% endblock %}
{% block user_nave %}
    <li><a href="setting.html"><i class="fa fa-gear"></i></a></li>
{% endblock %}
{% block main_content %}
    <div class="empty-1"></div>
    <div class="row">
        <div class="col s12 l8 offset-l2 ">
            <table class="responsive-table striped">
                <tr>
                    <td>Name</td>
                    <td>{{ user.name }}</td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>{{ user.username }}</td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <td>Public Key</td>
                    <td>{{ user.userprofile.public_key }}</td>
                </tr>
                <tr>
                    <td>Private Key</td>
                    <td>{{ user.userprofile.private_key }}</td>
                </tr>
                <tr>
                    <td>Date Joined</td>
                    <td>{{ user.date_joined }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="empty-2"></div>
    <div class="empty-2"></div>
{% endblock %}

website/templates/user/register.html
<!DOCTYPE html>
{% extends 'website/base.html' %}
{% block main_content %}
    <div class="row center">
        <h4>Register</h4>
        <p style="color: red">{{ form_errors }}</p>
        <form method="post" action="{% url 'website:user_reg' %}" class="col s12">
            {% csrf_token %}
{#            {{ profile_form }}#}
            <div class="row cyan-text text-darken-2">
                <div class="empty-1"></div>
                <div class="input-field col s6 offset-s3">
                    <i class="fa fa-user prefix"></i>
                    {{ user_form.username }}
                    <label for="icon_email">Username</label>
                </div>
                <div class="input-field col s6 offset-s3">
                    <i class="fa fa-at prefix"></i>
                    {{ user_form.email }}
                    <label for="icon_prefix">Email</label>
                </div>
                <div class="input-field col s6 offset-s3">
                    <i class="fa fa-key prefix"></i>
                    {{ user_form.password }}
                    <label for="icon_prefix">Password</label>
                </div>
                <div class="input-field col s6 offset-s3">
                    <input type="submit" value="REGISTER" class="btn btn-large">
                </div>
                <div class="input-field col s6 offset-s3">
                    If you already have account please <a href="{% url 'website:user_login' %}">Login</a>.
                </div>
            </div>
        </form>
    </div>
    <div class="empty-2"></div>
{% endblock %}